services:
  server:
    build:
      context: ./
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://SkyRouteAdmin:SkyR0uteP@55w0rd@db:5432/SkyRoute
    env_file:
      - apps/server/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: sh -c "npx prisma migrate dev --name init && npx prisma db seed && npm start"


  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      server:
        condition: service_healthy

    environment:
      - VITE_API_URL=http://localhost:8080

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: SkyRouteAdmin
      POSTGRES_PASSWORD: SkyR0uteP@55w0rd
      POSTGRES_DB: SkyRoute
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U SkyRouteAdmin -d SkyRoute"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  drone-sim-1:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=1
      - SIM_PHARMACY_ID=1
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-2:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=2
      - SIM_PHARMACY_ID=1
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-3:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=3
      - SIM_PHARMACY_ID=1
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-4:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=4
      - SIM_PHARMACY_ID=2
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-5:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=5
      - SIM_PHARMACY_ID=2
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-6:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=6
      - SIM_PHARMACY_ID=2
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-7:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=7
      - SIM_PHARMACY_ID=3
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-8:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=8
      - SIM_PHARMACY_ID=3
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure

  drone-sim-9:
    build:
      context: ./apps/drone-sim
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8080
      - SIM_DRONE_ID=9
      - SIM_PHARMACY_ID=3
    depends_on:
      server:
        condition: service_healthy
    restart: on-failure